jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ROGER_MANAGER:    [ROLE_ROGER_CMS_CONTENT_MANAGER, ROLE_ROGER_CMS_DESIGN_MANAGER]


    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin:
                        password: adminpass
                        roles:
                            - ROLE_ADMIN
                            - ROLE_ROGER_MANAGER
                            - ROLE_ROGER_CMS_MEDIA_MANAGER
                            - ROLE_ROGER_CMS_PAGE_MANAGER
                            - ROLE_ROGER_CMS_LAYOUT_MANAGER
                            - ROLE_ROGER_CMS_SNIPPET_MANAGER

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        roger_admin:
            pattern:    ^/admin
            http_basic:
                realm: "Secured Demo Area"
            logout:     ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
